// Code generated by "stringer -type BandMember ./03-stringer/kessoku/"; DO NOT EDIT.

package kessoku

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Bocchi-0]
	_ = x[Ryo-1]
	_ = x[Nijika-2]
	_ = x[Kita-3]
	_ = x[maxBand-4]
}

const _BandMember_name = "BocchiRyoNijikaKitamaxBand"

var _BandMember_index = [...]uint8{0, 6, 9, 15, 19, 26}

func (i BandMember) String() string {
	if i < 0 || i >= BandMember(len(_BandMember_index)-1) {
		return "BandMember(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _BandMember_name[_BandMember_index[i]:_BandMember_index[i+1]]
}
